# llm_context_os/tests/test_speculative_runner.py
import unittest
from unittest.mock import MagicMock, call
import typing as t

from llm_context_os.runners.base import BaseRunner
from llm_context_os.runners.speculative_runner import SpeculativeRunner

# Corrected MockRunner that implements abstract methods properly
class MockCallsRunner(BaseRunner):
    def __init__(self, name: str = "MockRunner"):
        self.name = name
        # These mocks will be called by the concrete methods below
        self.generate_mock_internal = MagicMock(return_value=f"Generated by {self.name}")
        self.stream_chunks_template = [f"S1-{name} ", f"S2-{name} ", f"S3-{name} ", f"S4-{name} "]
        self.stream_mock_internal = MagicMock(side_effect=lambda prompt, **kwargs: (chunk for chunk in self.stream_chunks_template))

        self.kv_cache_internal_state = {f'{name}_cache': 'initial_data'}
        self.export_kv_cache_mock_internal = MagicMock(return_value=self.kv_cache_internal_state)
        self.import_kv_cache_mock_internal = MagicMock()
        self.preload_kv_mock_internal = MagicMock() # For the non-abstract preload_kv

    # Concrete implementations of abstract methods from BaseRunner
    def generate(self, prompt: str, **kwargs) -> str:
        return self.generate_mock_internal(prompt, **kwargs)

    def stream(self, prompt: str, **kwargs) -> t.Generator[str, None, None]:
        return self.stream_mock_internal(prompt, **kwargs)

    def export_kv_cache(self) -> t.Any:
        return self.export_kv_cache_mock_internal()

    def import_kv_cache(self, cache_data: t.Any) -> None:
        # Simulate storing imported cache if needed for test assertions later
        self.kv_cache_internal_state = cache_data
        self.import_kv_cache_mock_internal(cache_data)

    # Override optional method to make it mockable for call assertions
    def preload_kv(self, prompt: str, **kwargs) -> None:
        self.preload_kv_mock_internal(prompt, **kwargs)
        # Simulate preload updating the cache
        self.kv_cache_internal_state = {f'{self.name}_preloaded_with': prompt[:10]}


class TestSpeculativeRunner(unittest.TestCase):
    def setUp(self):
        self.draft_runner = MockCallsRunner(name="DraftTestRunner")
        self.target_runner = MockCallsRunner(name="TargetTestRunner")

        # Reset mocks on the mock instances themselves before each test
        self.draft_runner.generate_mock_internal.reset_mock()
        self.draft_runner.stream_mock_internal.reset_mock()
        self.draft_runner.export_kv_cache_mock_internal.reset_mock()
        self.draft_runner.import_kv_cache_mock_internal.reset_mock()
        self.draft_runner.preload_kv_mock_internal.reset_mock()

        self.target_runner.generate_mock_internal.reset_mock()
        self.target_runner.stream_mock_internal.reset_mock()
        self.target_runner.export_kv_cache_mock_internal.reset_mock()
        self.target_runner.import_kv_cache_mock_internal.reset_mock()
        self.target_runner.preload_kv_mock_internal.reset_mock()

        # Reconfigure default return/side_effect values after reset
        self.draft_runner.generate_mock_internal.return_value = f"Generated by {self.draft_runner.name}"
        self.draft_runner.stream_mock_internal.side_effect=lambda prompt, **kwargs: (chunk for chunk in self.draft_runner.stream_chunks_template)
        self.draft_runner.kv_cache_internal_state = {f'{self.draft_runner.name}_cache': 'initial_draft_data'}
        self.draft_runner.export_kv_cache_mock_internal.return_value = self.draft_runner.kv_cache_internal_state

        self.target_runner.generate_mock_internal.return_value = f"Generated by {self.target_runner.name}"
        self.target_runner.stream_mock_internal.side_effect=lambda prompt, **kwargs: (chunk for chunk in self.target_runner.stream_chunks_template)
        self.target_runner.kv_cache_internal_state = {f'{self.target_runner.name}_cache': 'initial_target_data'}
        self.target_runner.export_kv_cache_mock_internal.return_value = self.target_runner.kv_cache_internal_state

        self.spec_runner = SpeculativeRunner(
            draft_runner=self.draft_runner,
            target_runner=self.target_runner,
            speculative_k=3
        )

    def test_instantiation(self):
        self.assertIsNotNone(self.spec_runner)
        self.assertEqual(self.spec_runner.draft_runner, self.draft_runner)
        self.assertEqual(self.spec_runner.target_runner, self.target_runner)
        self.assertEqual(self.spec_runner.speculative_k, 3)

    def test_generate_delegation(self):
        test_prompt = "Test prompt for generate"
        self.target_runner.generate_mock_internal.return_value = "Final output from TargetTestRunner" # Specific for this test

        result = self.spec_runner.generate(test_prompt, temperature=0.5)

        # Check calls on the internal mock attributes
        self.draft_runner.generate_mock_internal.assert_called_once_with(test_prompt, max_new_tokens=15, temperature=0.5)

        expected_target_prompt = test_prompt + "draft1 draft2 draft3 "
        self.target_runner.generate_mock_internal.assert_called_once_with(expected_target_prompt, temperature=0.5)
        self.assertEqual(result, "Final output from TargetTestRunner")

    def test_stream_delegation(self):
        test_prompt = "Test prompt for stream"

        # Use the templates defined in MockCallsRunner, no need to redefine here if setUp is correct
        # self.draft_runner.stream_chunks_template = ["D1 ", "D2 ", "D3 ", "D4 ", "D5 "]
        # self.draft_runner.stream_mock_internal.side_effect = lambda prompt, **kwargs: (chunk for chunk in self.draft_runner.stream_chunks_template)

        # self.target_runner.stream_chunks_template = ["T1 ", "T2 ", "T3 ", "T4 "]
        # self.target_runner.stream_mock_internal.side_effect = lambda prompt, **kwargs: (chunk for chunk in self.target_runner.stream_chunks_template)

        collected_chunks = list(self.spec_runner.stream(test_prompt, max_tokens=100))

        self.draft_runner.stream_mock_internal.assert_called_once_with(test_prompt, max_new_tokens=15, max_tokens=100)
        self.target_runner.stream_mock_internal.assert_called_once_with(test_prompt, max_tokens=100)

        # Expected stream based on default stream_chunks_template in MockCallsRunner constructor
        expected_draft_chunks = [f"S1-{self.draft_runner.name} ", f"S2-{self.draft_runner.name} ", f"S3-{self.draft_runner.name} "] # k=3
        expected_target_chunks = self.target_runner.stream_chunks_template
        expected_full_stream = expected_draft_chunks + expected_target_chunks + [" [EndOfSpecStream]"]
        self.assertEqual(collected_chunks, expected_full_stream)


    def test_kv_cache_export_delegation(self):
        self.target_runner.kv_cache_internal_state = {"target_specific_key": "target_cache_content_export"}
        self.target_runner.export_kv_cache_mock_internal.return_value = self.target_runner.kv_cache_internal_state

        result = self.spec_runner.export_kv_cache()

        self.target_runner.export_kv_cache_mock_internal.assert_called_once()
        self.draft_runner.export_kv_cache_mock_internal.assert_not_called()
        self.assertEqual(result, {"target_specific_key": "target_cache_content_export"})

    def test_kv_cache_import_delegation(self):
        test_cache_data = {"shared_key": "shared_cache_data_for_import"}
        self.spec_runner.import_kv_cache(test_cache_data)

        self.draft_runner.import_kv_cache_mock_internal.assert_called_once_with(test_cache_data)
        self.target_runner.import_kv_cache_mock_internal.assert_called_once_with(test_cache_data)

        self.assertEqual(self.draft_runner.kv_cache_internal_state, test_cache_data)
        self.assertEqual(self.target_runner.kv_cache_internal_state, test_cache_data)


    def test_preload_kv_delegation(self):
        test_prompt = "Test preload prompt for speculative"
        self.spec_runner.preload_kv(test_prompt, some_kwarg="preload_value")

        self.draft_runner.preload_kv_mock_internal.assert_called_once_with(test_prompt, some_kwarg="preload_value")
        self.target_runner.preload_kv_mock_internal.assert_called_once_with(test_prompt, some_kwarg="preload_value")

        self.assertEqual(self.draft_runner.kv_cache_internal_state, {f'{self.draft_runner.name}_preloaded_with': test_prompt[:10]})
        self.assertEqual(self.target_runner.kv_cache_internal_state, {f'{self.target_runner.name}_preloaded_with': test_prompt[:10]})


if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)
